export const SET_DEALS = "SET_DEALS";
export const MORE_DEALS_LOADED = "MORE_DEAL_LOADED";

export const BIG_LOADER_START = "BIG_LOADER_START";
export const BIG_LOADER_STOP = "BIG_LOADER_STOP";
export const LOADING_MORE_DEALS_START = "LOADING_MORE_DEALS_START";
export const LOADING_MORE_DEALS_STOP = "LOADING_MORE_DEALS_STOP";
